{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paloma.secretName" . }}
  labels:
    {{- include "paloma.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.secrets.sourceAdminTokenKey }}: {{ .Values.backend.secrets.inline.sourceAdminToken | quote }}
  {{ .Values.backend.secrets.targetAdminTokenKey }}: {{ .Values.backend.secrets.inline.targetAdminToken | quote }}
{{- end }}